#enable swagger
springdoc.swagger-ui.enabled=true
# path swagger, chi can go localhost:8080/swagger
springdoc.swagger-ui.path=/swagger

#SQL
spring.datasource.url=jdbc:mysql://localhost:3306/training_project_management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# auto gen table, column
spring.jpa.hibernate.ddl-auto=update

# run create table and file resources/data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#show statistics SQL
spring.jpa.properties.hibernate.generate_statistics=true


