spring.application.name=be-project-management3
server.port=8082

#change environment
spring.profiles.active=local

# sort controller theo alpha
springdoc.swagger-ui.tags-sorter=alpha

spring.servlet.multipart.max-file-size=100MB

logging.file.name=log/app.log
logging.pattern.file=%d %p %c{1.} [%t] %m%n
logging.pattern.console=%d {HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

SECRET_KEY=fdagvbvfddfbdfbfdbfdbdfbfdfaadfadgdsgsgdsgdsgdsgsdrerqeqreqadfaf
