#disable swagger
springdoc.swagger-ui.enabled=false

#SQL
spring.datasource.url=jdbc:mysql://localhost:3306/training_project_management_prod?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
#diasble show SQL
spring.jpa.show-sql=false
